=== socjordi/geoquadtree/geoquadtree-0.9.0/wms/geoquadtreeserver.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT GeoQuadTreeServer (Service, Layer*)>

<!-- The Name is typically for machine-to-machine communication. -->
<!ELEMENT Name (#PCDATA) >

<!-- The Title is for informative display to a human. -->
<!ELEMENT Title (#PCDATA) >

<!-- The abstract is a longer narrative description of an object. -->
<!ELEMENT Abstract (#PCDATA) > 

<!ELEMENT Service (Title, Abstract?, KeywordList?,
                   ContactInformation?, Fees?, AccessConstraints?,
                   MaxWidth?, MaxHeight?, Logo?) >

<!-- List of keywords or keyword phrases to help catalog searching. -->
<!ELEMENT KeywordList (Keyword*) >

<!-- A single keyword or phrase. -->
<!ELEMENT Keyword (#PCDATA) >

<!-- Information about a contact person for the service. -->
<!ELEMENT ContactInformation  (ContactPersonPrimary?, ContactPosition?,
                               ContactAddress?, ContactVoiceTelephone?,
                               ContactFacsimileTelephone?,
                               ContactElectronicMailAddress?) >

<!--The primary contact person.-->
<!ELEMENT ContactPersonPrimary  (ContactPerson, ContactOrganization) >

<!--The person to contact.-->
<!ELEMENT ContactPerson  (#PCDATA) >

<!--The organization supplying the service.-->
<!ELEMENT ContactOrganization  (#PCDATA) >

<!--The position title for the contact person.-->
<!ELEMENT ContactPosition  (#PCDATA) >

<!--The address for the contact supplying the service.-->
<!ELEMENT ContactAddress  (AddressType,Address,City,StateOrProvince,PostCode,
               Country) >

<!--The type of address.-->
<!ELEMENT AddressType  (#PCDATA) >

<!--The street address.-->
<!ELEMENT Address  (#PCDATA) >

<!--The address city.-->
<!ELEMENT City  (#PCDATA) >

<!--The state or province.-->
<!ELEMENT StateOrProvince  (#PCDATA) >

<!--The zip or postal code.-->
<!ELEMENT PostCode  (#PCDATA) >

<!--The address country.-->
<!ELEMENT Country  (#PCDATA) >

<!--Contact telephone number.-->
<!ELEMENT ContactVoiceTelephone  (#PCDATA) >

<!--The contact fax number.-->
<!ELEMENT ContactFacsimileTelephone  (#PCDATA) >

<!--The e-mail address for the contact.-->
<!ELEMENT ContactElectronicMailAddress  (#PCDATA) >

<!-- Elements indicating what fees or access constraints are imposed. -->
<!ELEMENT Fees (#PCDATA)>
<!ELEMENT AccessConstraints (#PCDATA)>

<!ELEMENT MaxWidth (#PCDATA)>
<!ELEMENT MaxHeight (#PCDATA)>
<!ELEMENT Logo (#PCDATA)>

<!ELEMENT Description (#PCDATA) >

<!ELEMENT Type (#PCDATA) >
<!ELEMENT Definition (#PCDATA) >

<!ELEMENT SRS EMPTY>
<!ATTLIST SRS 
          Name CDATA #REQUIRED
          Path CDATA #REQUIRED>

<!ELEMENT Layer (SRS*, GeoQuadTree*)>
<!ATTLIST Layer 
          Name CDATA #REQUIRED
          Title CDATA #REQUIRED>

<!ELEMENT GeoQuadTree EMPTY>
<!ATTLIST GeoQuadTree
          Path CDATA #REQUIRED
          WebPath CDATA #REQUIRED
          MinResX CDATA #REQUIRED
          MinResY CDATA #REQUIRED
          MaxResX CDATA #REQUIRED
          MaxResY CDATA #REQUIRED>

=== socjordi/geoquadtree/geoquadtree-0.9.0/wms/geoquadtreeserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GeoQuadTreeServer SYSTEM "geoquadtreeserver.dtd">

<GeoQuadTreeServer>

  <Service>
    <Title>GeoQuadTree WMS Server</Title>
    <Abstract>This is an OGC-compliant Map Service served by geoquadtree.org</Abstract>
    <ContactInformation>
      <ContactPersonPrimary>
        <ContactPerson>Jordi</ContactPerson>
        <ContactOrganization>geoquadtree.org</ContactOrganization>
      </ContactPersonPrimary>
      <ContactElectronicMailAddress>geoquadtree@gmail.com</ContactElectronicMailAddress>
    </ContactInformation>
    <Fees>Free</Fees>
    <AccessConstraints>None, unless abused</AccessConstraints>
    <MaxWidth>2000</MaxWidth>
    <MaxHeight>2000</MaxHeight>
    <Logo>/etc/geoquadtree/logo.png</Logo>
  </Service>

  <Layer Name="bmng" Title="Blue Marble Next Generation">
    <SRS Name="EPSG:4326" Path="/etc/geoquadtree/epsg4326.prj" />
    <GeoQuadTree Path="/home/jordi/geoquadtree/tutorials/bmng_2km_60px_per_dg/bmng.gqt" WebPath="/geoquadtrees/bmng" MinResX="0" MinResY="0" MaxResX="1.0" MaxResY="1.0" />
  </Layer>

  <Layer Name="bt5m" Title="Base topogrÃ fica de Catalunya 1:5 000">
    <SRS Name="EPSG:23031" Path="/etc/geoquadtree/epsg23031_icc.prj" />
    <SRS Name="EPSG:4326" Path="/etc/geoquadtree/epsg4326.prj" />
    <GeoQuadTree Path="/home/jordi/geoquadtree/tutorials/bt5m/bt5m.gqt" WebPath="/geoquadtrees/bt5m" MinResX="0" MinResY="0" MaxResX="1.0" MaxResY="1.0" />
  </Layer>

</GeoQuadTreeServer>
